# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: tube-alert_development
  pool: 5
  username: bitley
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: tube-alert_test
  pool: 5
  username: bitley
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: tube-alert_production
  pool: 5
  username: bitley
  password:
